name: "PR: Test"

on:
  pull_request:
    types: [opened, synchronize, reoppened]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2

      - uses: actions/checkout@v2

      - name: Install dependecies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Harman's Code Coverage Report
        uses: hrgui/lcov-reporter-action@v0.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
